version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 20

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U workzorauser -d workzoradb" ]
      interval: 5s
      timeout: 5s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_healthy
      redis:
        condition: service_healthy

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=workzorauser
      - POSTGRES_PASSWORD=J95jACtFtadE
      - POSTGRES_DB=workzoradb
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_healthy
      redis:
        condition: service_healthy

  project-service:
    build: ./project-service
    container_name: project-service
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=workzorauser
      - POSTGRES_PASSWORD=J95jACtFtadE
      - POSTGRES_DB=workzoradb
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_healthy
      redis:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "${API_PORT}:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      auth-service:
        condition: service_started

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1025" ]
      interval: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5

volumes:
  auth_pgdata:
  pgadmin_data:
